/*
volturi.introduceYourself();
volturi.kill();
volturi.love();
volturi.attack();
volturi.tellAJoke();
*/
/*
guy1.introduceYourself();
guy1.hunt();
guy1.love();
guy1.transform();
guy1.tellUrFavoriteSWCharacter();
guy1.tellUrFavoriteColor();
*/
/*
girl.introduceYourself();
girl.hunt();
girl.love();
girl.tellYourFavoriteHobby();
girl.tellUrReligion();
girl.tellUrFavoriteSWCharacter();
girl.tellWhatULikeTheMostinYoda();
*/
/*
guy2.introduceYourself();
guy2.hunt();
guy2.love();
guy2.tellAge();
console.log(guy2.age);
guy2.useASuperpower();
guy2.tellUrFavoriteSWCharacter();
guy2.tellWhatULikeTheMostinYoda();
*/
